name: social_media_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 < 4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  firebase_core: ^3.4.0
  firebase_auth: 5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  file_picker: ^8.1.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo2.png"
