// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWIXC8XJLOIkDg6hLYV0wgPsmPPxAXhm4',
    appId: '1:201290122287:web:045d73ce5f56352790f2da',
    messagingSenderId: '201290122287',
    projectId: 'link-app-75039',
    authDomain: 'link-app-75039.firebaseapp.com',
    storageBucket: 'link-app-75039.appspot.com',
    measurementId: 'G-R07C4H5PTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5lIMz4MYFGP_Mcu1jNnLOagFOA6X7br0',
    appId: '1:201290122287:android:4cfa83957d26158490f2da',
    messagingSenderId: '201290122287',
    projectId: 'link-app-75039',
    storageBucket: 'link-app-75039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykEJry_qI4TdvyLu6EZ4kytneh_LRsTs',
    appId: '1:201290122287:ios:502c06b2eaaff21590f2da',
    messagingSenderId: '201290122287',
    projectId: 'link-app-75039',
    storageBucket: 'link-app-75039.appspot.com',
    iosBundleId: 'com.bytetalk.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykEJry_qI4TdvyLu6EZ4kytneh_LRsTs',
    appId: '1:201290122287:ios:502c06b2eaaff21590f2da',
    messagingSenderId: '201290122287',
    projectId: 'link-app-75039',
    storageBucket: 'link-app-75039.appspot.com',
    iosBundleId: 'com.bytetalk.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWIXC8XJLOIkDg6hLYV0wgPsmPPxAXhm4',
    appId: '1:201290122287:web:dbb5f5672eda454290f2da',
    messagingSenderId: '201290122287',
    projectId: 'link-app-75039',
    authDomain: 'link-app-75039.firebaseapp.com',
    storageBucket: 'link-app-75039.appspot.com',
    measurementId: 'G-VVVB7DZ7DN',
  );
}
